### ISSUE TITLE
JIT-related segmentation fault issue when building rabbitmq on arm64

### ISSUE THREAD

**Issue by NikolayMetchev** [ZCube/bitnami-compat#54]
Hello I am trying to build the rabbitmq apple silicone image and I get a segmentation fault
I am running this on a Macbook Pro M1.
macOS Monterey 12.6.2

```
36 1043.0             -e 's;%INETS_VSN%;7.5.3;' \
#36 1043.0           /usr/local/src/otp-24.3.4/erts/start_scripts/start_all_example.rel.src > /usr/local/src/otp-24.3.4/erts/start_scripts/start_all_example.rel
#36 1043.0 sed -e 's;%SYS_VSN%;24;' \
#36 1043.0             -e 's;%ERTS_VSN%;12.3.2;' \
#36 1043.0             -e 's;%KERNEL_VSN%;8.3.2;' \
#36 1043.0             -e 's;%STDLIB_VSN%;3.17.2;' \
#36 1043.0           /usr/local/src/otp-24.3.4/erts/start_scripts/no_dot_erlang.rel.src > /usr/local/src/otp-24.3.4/erts/start_scripts/no_dot_erlang.rel
#36 1043.1 /usr/bin/install -c -d /usr/local/src/otp-24.3.4/erts/start_scripts/tmp
#36 1043.1 ( cd /usr/local/src/otp-24.3.4/erts/start_scripts/tmp && \
#36 1043.1 erlc -W   -I/usr/local/src/otp-24.3.4/lib/kernel/ebin -I/usr/local/src/otp-24.3.4/lib/stdlib/ebin -I/usr/local/src/otp-24.3.4/lib/sasl/ebin +no_warn_sasl -o /usr/local/src/otp-24.3.4/erts/start_scripts /usr/local/src/otp-24.3.4/erts/start_scripts/start_clean.rel )
#36 1043.5 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#36 1043.5 Segmentation fault
#36 1043.5 make[2]: *** [Makefile:84: /usr/local/src/otp-24.3.4/erts/start_scripts/start_clean.script] Error 139
#36 1043.5 make[2]: Leaving directory '/usr/local/src/otp-24.3.4/erts/start_scripts'
#36 1043.5 make[1]: *** [Makefile:67: local_setup] Error 2
#36 1043.5 make[1]: Leaving directory '/usr/local/src/otp-24.3.4/erts'
#36 1043.5 make: *** [Makefile:1070: local_setup] Error 2
#36 ERROR: process "/bin/bash -o pipefail -c set -eux; \t\tsavedAptMark=\"$(apt-mark showmanual)\"; \tapt-get update; \tapt-get install --yes --no-install-recommends \t\tautoconf \t\tca-certificates \t\tdpkg-dev \t\tgcc \t\tg++ \t\tgnupg \t\tlibncurses5-dev \t\tmake \t\twget \t; \trm -rf /var/lib/apt/lists/*; \t\tOPENSSL_SOURCE_URL=\"https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz\"; \tOPENSSL_PATH=\"/usr/local/src/openssl-$OPENSSL_VERSION\"; \tOPENSSL_CONFIG_DIR=/usr/local/etc/ssl; \t\twget --progress dot:giga --output-document \"$OPENSSL_PATH.tar.gz.asc\" \"$OPENSSL_SOURCE_URL.asc\"; \twget --progress dot:giga --output-document \"$OPENSSL_PATH.tar.gz\" \"$OPENSSL_SOURCE_URL\"; \texport GNUPGHOME=\"$(mktemp -d)\"; \tfor key in $OPENSSL_PGP_KEY_IDS; do \t\tgpg --batch --keyserver \"$PGP_KEYSERVER\" --recv-keys \"$key\"; \tdone; \tgpg --batch --verify \"$OPENSSL_PATH.tar.gz.asc\" \"$OPENSSL_PATH.tar.gz\"; \tgpgconf --kill all; \trm -rf \"$GNUPGHOME\"; \techo \"$OPENSSL_SOURCE_SHA256 *$OPENSSL_PATH.tar.gz\" | sha256sum --check --strict -; \tmkdir -p \"$OPENSSL_PATH\"; \ttar --extract --file \"$OPENSSL_PATH.tar.gz\" --directory \"$OPENSSL_PATH\" --strip-components 1; \t\tcd \"$OPENSSL_PATH\"; \tdebMultiarch=\"$(dpkg-architecture --query DEB_HOST_MULTIARCH)\"; \tMACHINE=\"$(dpkg-architecture --query DEB_BUILD_GNU_CPU)\" \tRELEASE=\"4.x.y-z\" \tSYSTEM='Linux' \tBUILD='???' \t./config \t\t--openssldir=\"$OPENSSL_CONFIG_DIR\" \t\t--libdir=\"lib/$debMultiarch\" \t\t-Wl,-rpath=/usr/local/lib \t; \tmake -j \"$(getconf _NPROCESSORS_ONLN)\"; \tmake install_sw install_ssldirs; \tcd ..; \trm -rf \"$OPENSSL_PATH\"*; \tldconfig; \trmdir \"$OPENSSL_CONFIG_DIR/certs\" \"$OPENSSL_CONFIG_DIR/private\"; \tln -sf /etc/ssl/certs /etc/ssl/private \"$OPENSSL_CONFIG_DIR\"; \topenssl version; \t\tOTP_SOURCE_URL=\"https://github.com/erlang/otp/releases/download/OTP-$OTP_VERSION/otp_src_$OTP_VERSION.tar.gz\"; \tOTP_SHA256_URL=\"https://github.com/erlang/otp/releases/download/OTP-$OTP_VERSION/SHA256.txt\"; \tOTP_PATH=\"/usr/local/src/otp-$OTP_VERSION\"; \t\tmkdir -p \"$OTP_PATH\"; \twget --progress dot:giga --output-document \"$OTP_PATH.tar.gz\" \"$OTP_SOURCE_URL\"; \twget --progress dot:giga --output-document \"SHA256.txt\" \"$OTP_SHA256_URL\"; \tcat SHA256.txt | grep \"otp_src\" | awk -v version=$OTP_VERSION '{print $1,\"otp-\" version \".tar.gz\"}' | sha256sum --check --strict -; \ttar --extract --file \"$OTP_PATH.tar.gz\" --directory \"$OTP_PATH\" --strip-components 1; \t\tcd \"$OTP_PATH\"; \texport ERL_TOP=\"$OTP_PATH\"; \t./otp_build autoconf; \tCFLAGS=\"$(dpkg-buildflags --get CFLAGS)\"; export CFLAGS; \texport CFLAGS=\"$CFLAGS -Wl,-rpath=/usr/local/lib\"; \thostArch=\"$(dpkg-architecture --query DEB_HOST_GNU_TYPE)\"; \tbuildArch=\"$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)\"; \tdpkgArch=\"$(dpkg --print-architecture)\"; dpkgArch=\"${dpkgArch##*-}\"; \tjitFlag=; \tcase \"$dpkgArch\" in \t\tamd64) jitFlag='--enable-jit' ;; \t\tarm64) jitFlag='--disable-jit' ;; \tesac; \t./configure \t\t--host=\"$hostArch\" \t\t--build=\"$buildArch\" \t\t--disable-dynamic-ssl-lib \t\t--disable-hipe \t\t--disable-sctp \t\t--disable-silent-rules \t\t--enable-clock-gettime \t\t--enable-hybrid-heap \t\t--enable-kernel-poll \t\t--enable-shared-zlib \t\t--enable-smp-support \t\t--enable-threads \t\t--with-microstate-accounting=extra \t\t--without-common_test \t\t--without-debugger \t\t--without-dialyzer \t\t--without-diameter \t\t--without-edoc \t\t--without-erl_docgen \t\t--without-et \t\t--without-eunit \t\t--without-ftp \t\t--without-hipe \t\t--without-jinterface \t\t--without-megaco \t\t--without-observer \t\t--without-odbc \t\t--without-reltool \t\t--without-ssh \t\t--without-tftp \t\t--without-wx \t\t$jitFlag \t; \tmake -j \"$(getconf _NPROCESSORS_ONLN)\" GEN_OPT_FLGS=\"-O2 -fno-strict-aliasing\"; \tmake install; \tcd ..; \trm -rf \t\t\"$OTP_PATH\"* \t\t/usr/local/lib/erlang/lib/*/examples \t\t/usr/local/lib/erlang/lib/*/src \t; \t\tapt-mark auto '.*' > /dev/null; \t[ -z \"$savedAptMark\" ] || apt-mark manual $savedAptMark; \tfind /usr/local -type f -executable -exec ldd '{}' ';' \t\t| awk '/=>/ { print $(NF-1) }' \t\t| sort -u \t\t| grep -v libcrypto \t\t| grep -v libssl \t\t| xargs -r dpkg-query --search \t\t| cut -d: -f1 \t\t| sort -u \t\t| xargs -r apt-mark manual \t; \tapt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \t\topenssl version; \terl -noshell -eval 'io:format(\"~p~n~n~p~n~n\", [crypto:supports(), ssl:versions()]), init:stop().'" did not complete successfully: exit code: 2
------
 > importing cache manifest from 769032674102.dkr.ecr.us-east-1.amazonaws.com/mirror/docker.io/bitnami/rabbitmqrabbitmq:3.9:
------
------
 > [linux/amd64 stage-1  6/16] RUN set -eux; 		savedAptMark="$(apt-mark showmanual)"; 	apt-get update; 	apt-get install --yes --no-install-recommends 		autoconf 		ca-certificates 		dpkg-dev 		gcc 		g++ 		gnupg 		libncurses5-dev 		make 		wget 	; 	rm -rf /var/lib/apt/lists/*; 		OPENSSL_SOURCE_URL="https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz"; 	OPENSSL_PATH="/usr/local/src/openssl-$OPENSSL_VERSION"; 	OPENSSL_CONFIG_DIR=/usr/local/etc/ssl; 		wget --progress dot:giga --output-document "$OPENSSL_PATH.tar.gz.asc" "$OPENSSL_SOURCE_URL.asc"; 	wget --progress dot:giga --output-document "$OPENSSL_PATH.tar.gz" "$OPENSSL_SOURCE_URL"; 	export GNUPGHOME="$(mktemp -d)"; 	for key in $OPENSSL_PGP_KEY_IDS; do 		gpg --batch --keyserver "$PGP_KEYSERVER" --recv-keys "$key"; 	done; 	gpg --batch --verify "$OPENSSL_PATH.tar.gz.asc" "$OPENSSL_PATH.tar.gz"; 	gpgconf --kill all; 	rm -rf "$GNUPGHOME"; 	echo "$OPENSSL_SOURCE_SHA256 *$OPENSSL_PATH.tar.gz" | sha256sum --check --strict -; 	mkdir -p "$OPENSSL_PATH"; 	tar --extract --file "$OPENSSL_PATH.tar.gz" --directory "$OPENSSL_PATH" --strip-components 1; 		cd "$OPENSSL_PATH"; 	debMultiarch="$(dpkg-architecture --query DEB_HOST_MULTIARCH)"; 	MACHINE="$(dpkg-architecture --query DEB_BUILD_GNU_CPU)" 	RELEASE="4.x.y-z" 	SYSTEM='Linux' 	BUILD='???' 	./config 		--openssldir="$OPENSSL_CONFIG_DIR" 		--libdir="lib/$debMultiarch" 		-Wl,-rpath=/usr/local/lib 	; 	make -j "$(getconf _NPROCESSORS_ONLN)"; 	make install_sw install_ssldirs; 	cd ..; 	rm -rf "$OPENSSL_PATH"*; 	ldconfig; 	rmdir "$OPENSSL_CONFIG_DIR/certs" "$OPENSSL_CONFIG_DIR/private"; 	ln -sf /etc/ssl/certs /etc/ssl/private "$OPENSSL_CONFIG_DIR"; 	openssl version; 		OTP_SOURCE_URL="https://github.com/erlang/otp/releases/download/OTP-$OTP_VERSION/otp_src_$OTP_VERSION.tar.gz"; 	OTP_SHA256_URL="https://github.com/erlang/otp/releases/download/OTP-$OTP_VERSION/SHA256.txt"; 	OTP_PATH="/usr/local/src/otp-$OTP_VERSION"; 		mkdir -p "$OTP_PATH"; 	wget --progress dot:giga --output-document "$OTP_PATH.tar.gz" "$OTP_SOURCE_URL"; 	wget --progress dot:giga --output-document "SHA256.txt" "$OTP_SHA256_URL"; 	cat SHA256.txt | grep "otp_src" | awk -v version=$OTP_VERSION '{print $1,"otp-" version ".tar.gz"}' | sha256sum --check --strict -; 	tar --extract --file "$OTP_PATH.tar.gz" --directory "$OTP_PATH" --strip-components 1; 		cd "$OTP_PATH"; 	export ERL_TOP="$OTP_PATH"; 	./otp_build autoconf; 	CFLAGS="$(dpkg-buildflags --get CFLAGS)"; export CFLAGS; 	export CFLAGS="$CFLAGS -Wl,-rpath=/usr/local/lib"; 	hostArch="$(dpkg-architecture --query DEB_HOST_GNU_TYPE)"; 	buildArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"; 	dpkgArch="$(dpkg --print-architecture)"; dpkgArch="${dpkgArch##*-}"; 	jitFlag=; 	case "$dpkgArch" in 		amd64) jitFlag='--enable-jit' ;; 		arm64) jitFlag='--disable-jit' ;; 	esac; 	./configure 		--host="$hostArch" 		--build="$buildArch" 		--disable-dynamic-ssl-lib 		--disable-hipe 		--disable-sctp 		--disable-silent-rules 		--enable-clock-gettime 		--enable-hybrid-heap 		--enable-kernel-poll 		--enable-shared-zlib 		--enable-smp-support 		--enable-threads 		--with-microstate-accounting=extra 		--without-common_test 		--without-debugger 		--without-dialyzer 		--without-diameter 		--without-edoc 		--without-erl_docgen 		--without-et 		--without-eunit 		--without-ftp 		--without-hipe 		--without-jinterface 		--without-megaco 	--without-observer 		--without-odbc 		--without-reltool 		--without-ssh 		--without-tftp 		--without-wx 		$jitFlag 	; 	make -j "$(getconf _NPROCESSORS_ONLN)" GEN_OPT_FLGS="-O2 -fno-strict-aliasing"; 	make install; 	cd ..; 	rm -rf 		"$OTP_PATH"* 		/usr/local/lib/erlang/lib/*/examples 		/usr/local/lib/erlang/lib/*/src 	; 		apt-mark auto '.*' > /dev/null; 	[ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; 	find /usr/local -type f -executable -exec ldd '{}' ';' 		| awk '/=>/ { print $(NF-1) }' 		| sort -u 		| grep -v libcrypto 		| grep -v libssl 		| xargs -r dpkg-query --search 		| cut -d: -f1 		| sort -u | xargs -r apt-mark manual 	; 	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; 		openssl version; 	erl -noshell -eval 'io:format("~p~n~n~p~n~n", [crypto:supports(), ssl:versions()]), init:stop().':
#36 1043.1 /usr/bin/install -c -d /usr/local/src/otp-24.3.4/erts/start_scripts/tmp
#36 1043.1 ( cd /usr/local/src/otp-24.3.4/erts/start_scripts/tmp && \
#36 1043.1 erlc -W   -I/usr/local/src/otp-24.3.4/lib/kernel/ebin -I/usr/local/src/otp-24.3.4/lib/stdlib/ebin -I/usr/local/src/otp-24.3.4/lib/sasl/ebin +no_warn_sasl -o /usr/local/src/otp-24.3.4/erts/start_scripts /usr/local/src/otp-24.3.4/erts/start_scripts/start_clean.rel )
#36 1043.5 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
#36 1043.5 Segmentation fault
#36 1043.5 make[2]: *** [Makefile:84: /usr/local/src/otp-24.3.4/erts/start_scripts/start_clean.script] Error 139
#36 1043.5 make[2]: Leaving directory '/usr/local/src/otp-24.3.4/erts/start_scripts'
#36 1043.5 make[1]: *** [Makefile:67: local_setup] Error 2
#36 1043.5 make[1]: Leaving directory '/usr/local/src/otp-24.3.4/erts'
#36 1043.5 make: *** [Makefile:1070: local_setup] Error 2
------
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
Dockerfile.arm64:129
--------------------
 128 |     # libncurses5-dev: Required for Erlang/OTP new shell & observer_cli - https://github.com/zhongwencool/observer_cli
 129 | >>> RUN set -eux; \
 130 | >>> 	\

```

```
 278 | >>> 	\
 279 | >>> # Check that OpenSSL still works after purging build dependencies
 280 | >>> 	openssl version; \
 281 | >>> # Check that Erlang/OTP crypto & ssl were compiled against OpenSSL correctly
 282 | >>> 	erl -noshell -eval 'io:format("~p~n~n~p~n~n", [crypto:supports(), ssl:versions()]), init:stop().'
 283 |     
--------------------
ERROR: failed to solve: process "/bin/bash -o pipefail -c set -eux; \t\tsavedAptMark=\"$(apt-mark showmanual)\"; \tapt-get update; \tapt-get install --yes --no-install-recommends \t\tautoconf \t\tca-certificates \t\tdpkg-dev \t\tgcc \t\tg++ \t\tgnupg \t\tlibncurses5-dev \t\tmake \t\twget \t; \trm -rf /var/lib/apt/lists/*; \t\tOPENSSL_SOURCE_URL=\"https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz\"; \tOPENSSL_PATH=\"/usr/local/src/openssl-$OPENSSL_VERSION\"; \tOPENSSL_CONFIG_DIR=/usr/local/etc/ssl; \t\twget --progress dot:giga --output-document \"$OPENSSL_PATH.tar.gz.asc\" \"$OPENSSL_SOURCE_URL.asc\"; \twget --progress dot:giga --output-document \"$OPENSSL_PATH.tar.gz\" \"$OPENSSL_SOURCE_URL\"; \texport GNUPGHOME=\"$(mktemp -d)\"; \tfor key in $OPENSSL_PGP_KEY_IDS; do \t\tgpg --batch --keyserver \"$PGP_KEYSERVER\" --recv-keys \"$key\"; \tdone; \tgpg --batch --verify \"$OPENSSL_PATH.tar.gz.asc\" \"$OPENSSL_PATH.tar.gz\"; \tgpgconf --kill all; \trm -rf \"$GNUPGHOME\"; \techo \"$OPENSSL_SOURCE_SHA256 *$OPENSSL_PATH.tar.gz\" | sha256sum --check --strict -; \tmkdir -p \"$OPENSSL_PATH\"; \ttar --extract --file \"$OPENSSL_PATH.tar.gz\" --directory \"$OPENSSL_PATH\" --strip-components 1; \t\tcd \"$OPENSSL_PATH\"; \tdebMultiarch=\"$(dpkg-architecture --query DEB_HOST_MULTIARCH)\"; \tMACHINE=\"$(dpkg-architecture --query DEB_BUILD_GNU_CPU)\" \tRELEASE=\"4.x.y-z\" \tSYSTEM='Linux' \tBUILD='???' \t./config \t\t--openssldir=\"$OPENSSL_CONFIG_DIR\" \t\t--libdir=\"lib/$debMultiarch\" \t\t-Wl,-rpath=/usr/local/lib \t; \tmake -j \"$(getconf _NPROCESSORS_ONLN)\"; \tmake install_sw install_ssldirs; \tcd ..; \trm -rf \"$OPENSSL_PATH\"*; \tldconfig; \trmdir \"$OPENSSL_CONFIG_DIR/certs\" \"$OPENSSL_CONFIG_DIR/private\"; \tln -sf /etc/ssl/certs /etc/ssl/private \"$OPENSSL_CONFIG_DIR\"; \topenssl version; \t\tOTP_SOURCE_URL=\"https://github.com/erlang/otp/releases/download/OTP-$OTP_VERSION/otp_src_$OTP_VERSION.tar.gz\"; \tOTP_SHA256_URL=\"https://github.com/erlang/otp/releases/download/OTP-$OTP_VERSION/SHA256.txt\"; \tOTP_PATH=\"/usr/local/src/otp-$OTP_VERSION\"; \t\tmkdir -p \"$OTP_PATH\"; \twget --progress dot:giga --output-document \"$OTP_PATH.tar.gz\" \"$OTP_SOURCE_URL\"; \twget --progress dot:giga --output-document \"SHA256.txt\" \"$OTP_SHA256_URL\"; \tcat SHA256.txt | grep \"otp_src\" | awk -v version=$OTP_VERSION '{print $1,\"otp-\" version \".tar.gz\"}' | sha256sum --check --strict -; \ttar --extract --file \"$OTP_PATH.tar.gz\" --directory \"$OTP_PATH\" --strip-components 1; \t\tcd \"$OTP_PATH\"; \texport ERL_TOP=\"$OTP_PATH\"; \t./otp_build autoconf; \tCFLAGS=\"$(dpkg-buildflags --get CFLAGS)\"; export CFLAGS; \texport CFLAGS=\"$CFLAGS -Wl,-rpath=/usr/local/lib\"; \thostArch=\"$(dpkg-architecture --query DEB_HOST_GNU_TYPE)\"; \tbuildArch=\"$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)\"; \tdpkgArch=\"$(dpkg --print-architecture)\"; dpkgArch=\"${dpkgArch##*-}\"; \tjitFlag=; \tcase \"$dpkgArch\" in \t\tamd64) jitFlag='--enable-jit' ;; \t\tarm64) jitFlag='--disable-jit' ;; \tesac; \t./configure \t\t--host=\"$hostArch\" \t\t--build=\"$buildArch\" \t\t--disable-dynamic-ssl-lib \t\t--disable-hipe \t\t--disable-sctp \t\t--disable-silent-rules \t\t--enable-clock-gettime \t\t--enable-hybrid-heap \t\t--enable-kernel-poll \t\t--enable-shared-zlib \t\t--enable-smp-support \t\t--enable-threads \t\t--with-microstate-accounting=extra \t\t--without-common_test \t\t--without-debugger \t\t--without-dialyzer \t\t--without-diameter \t\t--without-edoc \t\t--without-erl_docgen \t\t--without-et \t\t--without-eunit \t\t--without-ftp \t\t--without-hipe \t\t--without-jinterface \t\t--without-megaco \t\t--without-observer \t\t--without-odbc \t\t--without-reltool \t\t--without-ssh \t\t--without-tftp \t\t--without-wx \t\t$jitFlag \t; \tmake -j \"$(getconf _NPROCESSORS_ONLN)\" GEN_OPT_FLGS=\"-O2 -fno-strict-aliasing\"; \tmake install; \tcd ..; \trm -rf \t\t\"$OTP_PATH\"* \t\t/usr/local/lib/erlang/lib/*/examples \t\t/usr/local/lib/erlang/lib/*/src \t; \t\tapt-mark auto '.*' > /dev/null; \t[ -z \"$savedAptMark\" ] || apt-mark manual $savedAptMark; \tfind /usr/local -type f -executable -exec ldd '{}' ';' \t\t| awk '/=>/ { print $(NF-1) }' \t\t| sort -u \t\t| grep -v libcrypto \t\t| grep -v libssl \t\t| xargs -r dpkg-query --search \t\t| cut -d: -f1 \t\t| sort -u \t\t| xargs -r apt-mark manual \t; \tapt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \t\topenssl version; \terl -noshell -eval 'io:format(\"~p~n~n~p~n~n\", [crypto:supports(), ssl:versions()]), init:stop().'" did not complete successfully: exit code: 2
2023/01/09 12:40:39 exit status 1
panic: exit status 1

goroutine 1 [running]:
log.Panic({0x140000ddc10?, 0x6?, 0x140001bea80?})
	/Users/nmetchev/.asdf/installs/golang/1.19.3/go/src/log/log.go:388 +0x64
github.com/zcube/bitnami-compat/cmd.glob..func1(0x10516d2e0?, {0x104aacd6d?, 0x4?, 0x4?})
	/Users/nmetchev/dev/bitnami-compat/cmd/build.go:165 +0xbe4
github.com/spf13/cobra.(*Command).execute(0x10516d2e0, {0x140001c6480, 0x4, 0x4})
	/Users/nmetchev/dev/gopath/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x4b8
github.com/spf13/cobra.(*Command).ExecuteC(0x10516d7e0)
	/Users/nmetchev/dev/gopath/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/nmetchev/dev/gopath/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/zcube/bitnami-compat/cmd.Execute()
	/Users/nmetchev/dev/bitnami-compat/cmd/root.go:47 +0x28
main.main()
	/Users/nmetchev/dev/bitnami-compat/main.go:27 +0x1c
exit status 2
```

**Comment by ZCube** [comment]
The issue is caused by jit support in erlang otp.
patches/erlang/24/docker/Dockerfile.install
```
	case "$dpkgArch" in \
		amd64) jitFlag='--enable-jit' ;; \
		arm64) jitFlag='--disable-jit' ;; \
	esac; \
```
Currently, github is building on amd64, so I was enabling jit on amd64, but I didn't expect to build directly on arm64.
Build by replacing enable-jit with disable-jit in that line.

I will work on a better solution over the weekend.

**Comment by ZCube** [comment]
관련된 이슈 : https://github.com/docker/for-mac/issues/6075

**Comment by NikolayMetchev** [comment]
This has worked. Thank you very much.
